---
schema-version: 1.0.0
destinations:
    - google.com
    - apple.com
globals:
    protocol: udp
    max-hops: 5
    number-queries: 3
    parallel-requests: 8
    timeout: 2s
    source-port: 33434
    interval: 1m0s
opentelemetry:
    destination: localhost.localdomain
    tls: false
    port: 4317
    grpc: true
healthcheck:
    path: /_healthcheck
    enabled: true
    port: 8080
